sudo: false

language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --skip-lock
  - pipenv install --dev --skip-lock

# command to run tests
script:
  - pipenv run pytest test_pykube.py
